baseurl = "http://tsforecasting-thiyanga.netlify.com/"
languageCode = "en-us"
title = "Time Series Forecasting"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Resources"
    url = "https://twitter.com/rstudio"

[params]
    description = ""

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = ""
    width = 50
    height = 50
    alt = ""

